env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2020
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
